const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
const base=process.env.AVATAR_TEST_URL||'http://127.0.0.1:18809',out='output/verification/';
(async()=>{const browser=await chromium.launch(),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 const source=await page.request.get('http://127.0.0.1:18808/api/runtime/sessions/a2bdfa359ef74baea13b6c93d651d77f/project'),project=(await source.json()).project;
 const created=await page.request.post(base+'/api/runtime/sessions',{data:{project,tts:{engine:'browser'},accepting:false,ai_enabled:false}});assert.equal(created.status(),201,await created.text());const sid=(await created.json()).session_id,stage=base+'/api/stage/sessions/'+sid;
 fs.writeFileSync(out+'avatar-actions-session.json',JSON.stringify({sid,url:base+'/web/player.html?session='+sid+'&prepare=1&mode=idle&background=%23eef1f8'}));
 const get=async()=>await(await page.request.get(stage)).json();
 const wait=async fn=>{for(let n=0;n<200;n++){const v=await get();if(fn(v))return v;await page.waitForTimeout(100)}throw Error('State timeout')};
 await page.goto(base+'/web/player.html?session='+sid+'&prepare=1&mode=idle&background=%23eef1f8');await page.waitForSelector('#broadcastLook input:enabled',{timeout:120000});
 assert(await page.locator('#apiSettings').isHidden());assert(await page.locator('#voiceConfig').isHidden());assert.equal(await page.locator('#stageControls').count(),0);assert(await page.locator('#notice').isHidden());
 const control=k=>page.locator('#broadcastLook [data-look='+k+']');
 await control('emotion').selectOption('sweat');await wait(v=>v.baseline.appearance.emotion==='sweat');
 await page.locator('[data-action=place-sweat]').click();
 const face=project.parts.find(p=>p.faceBase||/^face$/i.test(p.sourceLayerName||'')||/顔の下地|^face(?:$|[（(])/i.test(p.name||''));assert(face);
 const canvas=page.locator('#stage canvas');const r=await canvas.boundingBox(),v=await canvas.evaluate(c=>c.viewport),target={x:r.x+r.width*(face.x+face.width*.83-v.x)/v.width,y:r.y+r.height*(face.y+face.height*.48-v.y)/v.height};
 await page.mouse.click(target.x,target.y);await page.locator('.avatar-preview-edit [data-done]').click();await wait(v=>Math.abs(v.baseline.appearance.sweat_x-.33)<.03&&Math.abs(v.baseline.appearance.sweat_y+.02)<.03);
 await control('sweat_scale').evaluate(e=>e.value='.08');await control('sweat_scale').dispatchEvent('input');await wait(v=>v.baseline.appearance.sweat_scale===.08);
 await page.locator('#broadcastLook').scrollIntoViewIfNeeded();await page.screenshot({path:out+'avatar-sweat-position.png'});
 // Cancel restores position even after a drag has already reached the server.
 const old=(await get()).baseline.appearance;await page.locator('[data-action=place-sweat]').click();await page.mouse.click(target.x-20,target.y+20);await page.waitForTimeout(300);await page.locator('[data-cancel]').click();await wait(v=>v.baseline.appearance.sweat_x===old.sweat_x);
 await control('emotion').selectOption('blush');await wait(v=>v.baseline.appearance.emotion==='blush');
 await control('blush_scale').evaluate(e=>e.value='.7');await control('blush_scale').dispatchEvent('input');await control('blush_y').evaluate(e=>e.value='-.09');await control('blush_y').dispatchEvent('input');await wait(v=>v.baseline.appearance.blush_y===-.09);
 // Pick a visible garment pixel: no part dropdown selection is involved.
 await page.getByText('パーツの色を変える',{exact:true}).click();await page.locator('[data-action=pick]').click();
 const box=await canvas.boundingBox();await page.mouse.click(box.x+box.width*(project.width*.49-v.x)/v.width,box.y+box.height*(project.height*.85-v.y)/v.height);await page.waitForFunction(()=>document.querySelector('#broadcastLook [data-field=status]').textContent.includes('を選びました'),{},{timeout:30000});
 const picked=await page.locator('[data-field=part]').inputValue();assert(picked);await page.locator('[data-field=to]').fill('#6586bd');await page.locator('[data-action=color]').click();await wait(v=>v.baseline.appearance.colors.length===1);
 await page.waitForFunction(()=>document.querySelector('#broadcastLook [data-field=status]').textContent==='見た目を反映しました',{},{timeout:120000});await page.screenshot({path:out+'avatar-color-eyedropper.png'});
 const actions=page.locator('#avatarActions');await actions.locator('[data-kind]').selectOption('blush');await actions.locator('[data-name]').fill('照れ・位置調整済み');await actions.locator('[data-save]').click();await page.waitForFunction(()=>document.querySelector('#avatarActions [data-status]').textContent.startsWith('保存しました'));
 const blushId=await actions.locator('[data-saved]').inputValue();await actions.locator('[data-play]').click();await wait(v=>v.baseline.appearance.emotion==='none');await actions.locator('[data-play]').click();await wait(v=>v.baseline.appearance.emotion==='blush');
 await actions.locator('[data-kind]').selectOption('bounce');await actions.locator('[data-direction]').selectOption('up');await actions.locator('[data-duration]').fill('1');await actions.locator('[data-name]').fill('上へはずむ');await actions.locator('[data-save]').click();await page.waitForFunction(()=>document.querySelector('#avatarActions [data-status]').textContent.startsWith('保存しました'));const bounceId=await actions.locator('[data-saved]').inputValue();assert.notEqual(bounceId,blushId);
 await actions.locator('[data-play]').click();await page.waitForTimeout(1300);const runtime=await(await page.request.get(base+'/api/runtime/sessions/'+sid)).json();assert.equal(runtime.effect.preset,'bounce');assert.equal(runtime.effect.direction,'up');
 const obs=await browser.newPage({viewport:{width:900,height:900}});obs.on('pageerror',e=>errors.push(e.message));await obs.goto(base+'/web/player.html?session='+sid+'&display=1');await obs.waitForSelector('#stage canvas',{timeout:120000});await page.waitForTimeout(500);
 await page.bringToFront();await control('outline').check();await control('light').selectOption('sunset');await wait(v=>v.baseline.appearance.light==='sunset');
 await actions.scrollIntoViewIfNeeded();await page.screenshot({path:out+'avatar-actions-preparation.png'});
 await page.locator('#enterBroadcast').click();assert(await page.locator('#controls').isHidden());await page.waitForTimeout(200);await page.keyboard.press('Escape');assert(await page.locator('#controls').isVisible());
 const response=await page.request.post(base+'/api/avatar/sessions/'+sid+'/trigger',{data:{request_id:'browser-ink',preset_id:blushId}});assert.equal(response.status(),202);
 await obs.bringToFront();await obs.waitForTimeout(350);const alpha=await obs.evaluate(()=>{const c=document.querySelector('#stage canvas'),a=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let visible=0,clear=0;for(let i=3;i<a.length;i+=4){if(a[i]>200)visible++;if(a[i]===0)clear++;}return{visible,clear}});assert(alpha.visible>1000&&alpha.clear>1000);await obs.screenshot({path:out+'avatar-actions-obs.png'});
 assert.deepEqual(errors,[]);fs.writeFileSync(out+'avatar-actions-browser.json',JSON.stringify({sid,picked,blushId,bounceId,alpha,errors},null,2));console.log('Avatar UI passed',sid,picked,alpha);await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
