// Exercise the actual desktop settings UI with a controlled native bridge.
const {chromium}=require('playwright'),fs=require('node:fs'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch(),page=await browser.newPage();const rows=await(await page.request.get('http://127.0.0.1:18810/api/avatar/presets')).json();
const actions=rows.map(r=>({id:r.id,name:r.action.name})),combo=actions.find(a=>a.name==='笑顔の通信セット');assert(combo);
await page.addInitScript(({actions})=>{const config={data_dir:'E:/test',see_through_dir:'',port:18810,enabled:false,bindings:[0,1].map(i=>({shortcut:'Ctrl+Alt+'+i,index:0,mode:'select',cue_id:String(i).padStart(32,'0')}))};window.__TAURI__={event:{listen:async()=>{}},core:{invoke:async(name,args)=>{if(name==='desktop_sessions')return[{id:'test-session',name:'character',connected:true,expressions:['通常','笑顔'],actions}];if(name==='save_hotkeys'){window.saved=args;Object.assign(config,args);return;}if(name==='desktop_state')return{config,running:true,starting:false,settings_target:'test-session',settings_revision:1,registered:0,errors:[],last_event:'',url:'http://127.0.0.1:18810'};throw Error(name);}}};},{actions});
await page.route('http://desktop.test/**',route=>{const file=route.request().url().split('/').pop()||'index.html';route.fulfill({body:fs.readFileSync('desktop-ui/'+file),contentType:file.endsWith('.js')?'text/javascript':file.endsWith('.css')?'text/css':'text/html'});});
await page.goto('http://desktop.test/index.html');await page.waitForSelector('#bindings tr');
assert.equal(await page.locator('#bindings .expression').first().inputValue(),'cue:'+'0'.repeat(32));
await page.locator('#add').click();await page.locator('#bindings .expression').last().selectOption('cue:'+combo.id);await page.locator('#bindings .shortcut').last().fill('Ctrl+Alt+2');await page.locator('#enabled').check();await page.locator('#save').click();await page.waitForFunction(()=>window.saved);
const saved=await page.evaluate(()=>window.saved);assert.equal(saved.bindings[2].cue_id,combo.id);assert.equal(saved.target,'test-session');assert.equal(saved.enabled,true);console.log('Desktop UI pairs combined effects and default keys');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
