const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs');
(async()=>{const browser=await chromium.launch(),page=await browser.newPage();await page.goto('http://127.0.0.1:18811/web/effects-editor.css');
const result=await page.evaluate(async()=>{
 const project=(await(await fetch('/api/runtime/sessions/07d63c6946df4eb68c610c0d28128918/project')).json()).project,{prepareCanvasRenderer}=await import('/web/canvas-renderer.js'),{loopPose}=await import('/web/motion.js'),{regionWeight}=await import('/web/motion-region.js');
 const part=project.parts.find(p=>/bottomwear/.test(p.sourceLayerName||p.name)),region={cx:(part.x+part.width/2)/project.width,cy:(part.y+part.height*.8)/project.height,rx:part.width*.5/project.width,ry:part.height*.3/project.height};
 region.mask=Array.from({length:4096},(_,i)=>Math.round(255*regionWeight(region,i%64/63,Math.floor(i/64)/63)));part.secondaryMotion={enabled:true,amount:75,cycles:1,region};
 const renderers=[];for(const fast of [false,true])renderers.push(await prepareCanvasRenderer(structuredClone(project),1024,{clothScanlines:fast}));
 const timings=[],drawCalls=[];for(const r of renderers){const samples=[];let count=0;const original=CanvasRenderingContext2D.prototype.drawImage;CanvasRenderingContext2D.prototype.drawImage=function(...args){count++;return original.apply(this,args);};for(let i=0;i<40;i++){const start=performance.now();r.draw(loopPose(.3+i*.03,project.settings));if(i>20)samples.push(performance.now()-start);await new Promise(requestAnimationFrame);}CanvasRenderingContext2D.prototype.drawImage=original;drawCalls.push(count/40);timings.push(samples.reduce((a,b)=>a+b)/samples.length);}
 const diffs=[];for(const t of [0,.7,1.5,2.8,3.8]){const pose=loopPose(t,project.settings),pixels=renderers.map(r=>{r.draw(pose);return r.canvas.getContext('2d').getImageData(0,0,r.canvas.width,r.canvas.height).data;});let mean=0,alphaLost=0;for(let i=0;i<pixels[0].length;i++){mean+=Math.abs(pixels[0][i]-pixels[1][i]);if(i%4===3&&pixels[0][i]>150&&pixels[1][i]<10)alphaLost++;}diffs.push({t,mean:mean/pixels[0].length,alphaLost});}
 const image=renderers[1].canvas.toDataURL();renderers.forEach(r=>r.dispose());return {timings,drawCalls,diffs,image};
});fs.writeFileSync('output/verification/hem-fast-render.png',Buffer.from(result.image.split(',')[1],'base64'));delete result.image;fs.writeFileSync('output/verification/hem-warp-results.json',JSON.stringify(result,null,2));console.log(result);assert(result.drawCalls[1]<result.drawCalls[0]*.6,'regional sway must eliminate per-triangle redraws');assert(result.diffs.every(d=>d.mean<1&&d.alphaLost<600),'shape/alpha comparison');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
