const {chromium}=require('playwright'),assert=require('node:assert/strict');
const base=process.env.AVATAR_TEST_URL||'http://127.0.0.1:18811';
(async()=>{const browser=await chromium.launch(),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.setDefaultTimeout(60000);page.on('pageerror',e=>errors.push(e.message));
const project=(await(await page.request.get(base+'/api/runtime/sessions/07d63c6946df4eb68c610c0d28128918/project')).json()).project;
const created=await page.request.post(base+'/api/runtime/sessions',{data:{project,tts:{engine:'browser'},accepting:false,ai_enabled:false}});assert.equal(created.status(),201);const sid=(await created.json()).session_id;
await page.goto(base+'/web/effects-editor.html?session='+sid);await page.waitForFunction(()=>!document.querySelector('#effectPreview')?.disabled,{},{timeout:120000});const root=page.locator('#avatarActions');await page.locator('#effectAdd').click();await root.locator('[data-name]').fill('追加・削除を自動反映');
let requests=0;page.on('request',r=>{if(r.url().endsWith('/preview')&&r.method()==='POST')requests++;});
async function changed(click){const next=page.waitForResponse(r=>r.url().endsWith('/preview')&&r.request().method()==='POST');await click();const response=await next;assert.equal(response.status(),202);await page.waitForFunction(()=>!document.querySelector('#effectPreview').disabled);assert(await page.locator('#effectStop').isEnabled());return response.request().postDataJSON().action;}
const add=async kind=>{await root.locator('[data-kind]').selectOption(kind);return changed(()=>root.locator('[data-add]').click());};
const remove=kind=>changed(()=>root.locator('[data-component='+kind+']').locator('..').locator('.component-remove').click());
const alpha=()=>page.locator('#stage canvas').evaluate(c=>{const a=c.getContext('2d').getImageData(0,0,c.width,c.height).data;let n=0;for(let i=3;i<a.length;i+=4)if(a[i]>100)n++;return n;});
assert.deepEqual((await add('outline')).components.map(c=>c.kind),['outline']);
assert.deepEqual((await add('blush')).components.map(c=>c.kind),['outline','blush']);
assert.deepEqual((await remove('outline')).components.map(c=>c.kind),['blush']);
await page.locator('#effectStop').click();assert.deepEqual((await remove('blush')).components,[]);
assert.equal((await add('hide')).visibility,false);await page.waitForTimeout(600);assert.equal(await alpha(),0);
assert.equal((await remove('hide')).visibility,true);await page.waitForTimeout(600);assert(await alpha()>1000);
await page.locator('#effectStop').click();await root.locator('[data-behavior]').selectOption('timed');await root.locator('[data-duration]').fill('0.5');await add('outline');await page.waitForTimeout(1400);assert(await page.locator('#effectStop').isDisabled());
await root.locator('[data-behavior]').selectOption('select');await add('blush');await page.waitForTimeout(800);assert.equal(requests,8);
await root.locator('[data-name]').scrollIntoViewIfNeeded();await page.screenshot({path:'output/verification/effects-auto-preview.png'});
await page.locator('#effectStop').click();assert.deepEqual(errors,[]);console.log('Automatic preview: add, remove, stopped state, last removal, hide, timed expiry passed. No preset saved.');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
