const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
(async()=>{const browser=await chromium.launch(),page=await browser.newPage();await page.goto('http://127.0.0.1:18812/web/effects-editor.css');const result=await page.evaluate(async()=>{
const {createCharacterEffectsRenderer}=await import('/web/character-effects-renderer.js'),{createAvatarEffectsRenderer}=await import('/web/avatar-recipe.js'),{createBroadcastLookRenderer}=await import('/web/broadcast-look-renderer.js'),{defaultLook}=await import('/web/broadcast-look.js');
const source=document.createElement('canvas');source.width=source.height=256;const c=source.getContext('2d');c.fillStyle='#ea853a';c.fillRect(80,30,96,206);const project={width:256,height:256};const fx=createCharacterEffectsRenderer(source,project),cue={preset:'blocks',duration:4,strength:1,started_at:0,request_id:'blocks',direction:'up'};
const data=canvas=>canvas.getContext('2d').getImageData(0,0,256,256).data,count=canvas=>data(canvas).filter((v,i)=>i%4===3&&v>20).length,original=count(source),counts=[];
for(const t of [0,2,4]){fx.draw(cue,t);counts.push(count(fx.canvas));}
fx.draw({...cue,preset:'glitch'},1.62);const noisy=count(fx.canvas);fx.draw({...cue,preset:'glitch'},1);const quiet=count(fx.canvas);fx.draw({...cue,preset:'glitch',reduced:true},1.62);const reduced=count(fx.canvas);
const avatar=createAvatarEffectsRenderer(source,project);avatar.draw({...cue,preset:'bundle',recipe:{visibility:true,behavior:'select',components:[{kind:'blocks',direction:'up',duration:4,strength:1,speed:2}]}},2,{});const fast=count(avatar.canvas);
const look=createBroadcastLookRenderer(source),outlines=[];for(const layers of [1,2,3]){look.draw({...defaultLook(),outline:true,outline_layers:layers,outline_color_count:3,outline_color:'#ff0000',outline_color2:'#00ff00',outline_color3:'#0000ff',outline_width:12});outlines.push(count(look.canvas));}
fx.dispose();avatar.dispose();look.dispose();return {original,counts,noisy,quiet,reduced,fast,outlines};});console.log(result);assert.equal(result.counts[0],0);assert(result.counts[1]>0&&result.counts[1]<result.original);assert.equal(result.counts[2],result.original);assert(result.noisy>result.original);assert.equal(result.quiet,result.original);assert.equal(result.reduced,result.original);assert.equal(result.fast,result.original);assert(result.outlines[0]<result.outlines[1]&&result.outlines[1]<result.outlines[2]);fs.writeFileSync('output/verification/effects-new-render.json',JSON.stringify(result));await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
