const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch(),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.setDefaultTimeout(45000);page.on('pageerror',e=>{errors.push(e.message);console.log('PAGE ERROR',e.message)});
try{
const project=(await(await page.request.get('http://127.0.0.1:18811/api/runtime/sessions/07d63c6946df4eb68c610c0d28128918/project')).json()).project;
await page.goto('http://127.0.0.1:18814/');await page.locator('#projectInput').setInputFiles({name:'layers-test.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(project))});await page.locator('[data-tab=edit]').click();await page.waitForFunction(()=>document.querySelector('#artboard canvas.rig-preview'));await page.screenshot({path:'output/verification/shape-space.png'});
console.log('preview height',await page.locator('#eyesPreviewControl').boundingBox());
await page.locator('[data-tab=motion]').click();await page.locator('[data-motion-page=extra]').click();
for(const kind of ['ear','tail','wing']){assert.equal(await page.locator('#'+kind+'Target').inputValue(),'auto');assert(await page.locator('#'+kind+'Target option').count()>20);}
assert(await page.locator('#earPivotPick').isEnabled());await page.locator('#earPivotPick').click();await page.locator('#pivotPicker').waitFor();await page.locator('.pivot-picker-actions button').last().click();
await page.locator('#wingTarget').selectOption(await page.locator('#wingTarget option').nth(3).getAttribute('value'));assert(await page.locator('#wingPivotPick').isEnabled());await page.screenshot({path:'output/verification/accessory-targets.png'});
await page.locator('[data-tab=edit]').click();await page.locator('[data-edit-page=parts]').click();assert(!(await page.locator('#reviewArtworkSources').isVisible()));await page.locator('#editSvgLayers').click();const dialog=page.locator('.svg-layer-editor');await dialog.waitFor();const labels=await dialog.locator('[data-layer] option').allTextContents();console.log(labels);const option=dialog.locator('[data-layer] option').filter({hasText:'bottomwear'}).first();await dialog.locator('[data-layer]').selectOption(await option.getAttribute('value'));
const board=dialog.locator('[data-board]');let b=await board.boundingBox();await page.mouse.move(b.x+b.width*.5,b.y+b.height*.75);await page.mouse.wheel(0,-300);await page.screenshot({path:'output/verification/svg-layer-editor.png'});
await page.mouse.move(b.x+b.width*.5,b.y+b.height*.5);await page.mouse.down();await page.mouse.move(b.x+b.width*.5+30,b.y+b.height*.5,{steps:5});await page.mouse.up();assert(await dialog.locator('[data-undo]').isEnabled());await dialog.locator('[data-undo]').click();await dialog.locator('[data-redo]').click();await dialog.locator('[data-apply]').click();await dialog.waitFor({state:'detached'});await page.locator('#editSvgLayers').click();assert(await dialog.locator('[data-undo]').isDisabled());await dialog.locator('[data-cancel]').click();
assert.deepEqual(errors,[]);console.log('UI passed');
}catch(e){await page.screenshot({path:'output/verification/layer-edit-failure.png'});throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
