const {chromium}=require('playwright'),assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch(),page=await browser.newPage({viewport:{width:1480,height:1040}}),errors=[];page.setDefaultTimeout(45000);page.on('pageerror',e=>errors.push(e.message));try{
const project=(await(await page.request.get('http://127.0.0.1:18811/api/runtime/sessions/07d63c6946df4eb68c610c0d28128918/project')).json()).project;for(const p of project.parts)delete p.secondaryMotion;
await page.goto('http://127.0.0.1:18814/');await page.locator('#projectInput').setInputFiles({name:'menu-test.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(project))});await page.locator('[data-tab=edit]').click();await page.locator('[data-edit-page=parts]').click();await page.locator('#editSvgLayers').click();const d=page.locator('.svg-layer-editor');await d.waitFor();assert.equal(await d.locator('[data-other-opacity]').inputValue(),'70');
await d.locator('[data-layer]').selectOption(await d.locator('[data-layer] option').filter({hasText:'bottomwear'}).getAttribute('value'));
let id=await d.locator('[data-layer]').inputValue();assert.equal(await d.locator(`image[data-layer-id="${id}"]`).getAttribute('opacity'),'1');const other=d.locator(`image:not([data-layer-id="${id}"])`).first();assert.equal(await other.getAttribute('opacity'),'0.7');await page.screenshot({path:'output/verification/layer-context-opacity.png'});
await d.locator('[data-other-opacity]').fill('30');assert.equal(await other.getAttribute('opacity'),'0.3');await d.locator('[data-apply]').click();await d.waitFor({state:'detached'});await page.locator('#editSvgLayers').click();const next=await d.locator('[data-layer] option').first().getAttribute('value');await d.locator('[data-layer]').selectOption(next);assert.equal(await d.locator(`image[data-layer-id="${next}"]`).getAttribute('opacity'),'1','view dimming must not alter saved opacity');await d.locator('[data-cancel]').click();
await page.locator('[data-tab=motion]').click();await page.locator('[data-motion-page=extra]').click();assert.equal(await page.locator('#earsAccessoryControls').evaluate(e=>e.tagName),'SECTION');assert.equal(await page.locator('#earsAccessoryControls h3').innerText(),'耳のピコピコ');await page.locator('#earTarget').selectOption('none');await page.locator('#earTarget').selectOption('both');assert.equal(await page.locator('#earPivotTarget option').count(),2);assert(await page.locator('#earPivotPick').isEnabled());await page.locator('#earPivotTarget').selectOption(await page.locator('#earPivotTarget option').last().getAttribute('value'));await page.locator('#earPivotPick').click();await page.locator('#pivotPicker').waitFor();await page.locator('.pivot-picker-actions button').last().click();await page.screenshot({path:'output/verification/ears-paired-controls.png'});
await page.locator('[data-motion-page=iris]').click();assert(!(await page.locator('#headIdleDetails').isVisible()));for(const field of ['pitchSway','headNod','bodyFollow','neckPivotPick'])assert.equal(await page.locator('#'+field).evaluate(e=>e.closest('section').id),'headCoordinationControls');assert(await page.locator('#browMotionEnabled').isChecked());await page.locator('#neckPivotPick').scrollIntoViewIfNeeded();await page.screenshot({path:'output/verification/face-unified-controls.png'});
await page.locator('[data-motion-page=clothes]').click();const picker=page.locator('#secondaryMotionControls .motion-part-picker');async function choose(label){await picker.locator('summary').click();await picker.locator('button').filter({hasText:label}).first().click();}
await choose('bottomwear');await page.locator('#secondaryAdd').click();assert.equal(await page.locator('#secondaryAdded [data-motion-part]').count(),1);const first=page.locator('#secondaryAdded [data-motion-part]').first(),firstId=await first.getAttribute('data-motion-part');await first.locator('input').first().fill('60');
await choose('legwear');await page.locator('#secondaryAdd').click();assert.equal(await page.locator('#secondaryAdded [data-motion-part]').count(),2);assert.equal(await page.locator(`[data-motion-part="${firstId}"] input`).first().inputValue(),'60','adding another layer preserves settings');await page.screenshot({path:'output/verification/clothing-motion-list.png'});
await page.locator(`#secondaryAdded [data-motion-part]:not([data-motion-part="${firstId}"])`).getByRole('button',{name:'ブラシで補正'}).click();await page.locator('.motion-region-overlay').waitFor();await page.locator('.motion-region-actions [data-cancel]').click();await page.locator(`#secondaryAdded [data-motion-part]:not([data-motion-part="${firstId}"])`).getByRole('button',{name:'揺れを外す'}).click();assert.equal(await page.locator('#secondaryAdded [data-motion-part]').count(),1);assert.equal(await page.locator(`[data-motion-part="${firstId}"] input`).first().inputValue(),'60');
assert.deepEqual(errors,[]);console.log('View-only dimming; both-ear selection and individual pivots; unified face controls; brow default; two independent clothing layers, range correction and remove passed');
}catch(e){await page.screenshot({path:'output/verification/motion-menu-failure.png'});throw e;}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
