const {chromium}=require('playwright'),assert=require('node:assert/strict');
const base='http://127.0.0.1:18812';
(async()=>{const browser=await chromium.launch(),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.setDefaultTimeout(90000);page.on('pageerror',e=>errors.push(e.message));
const project=(await(await page.request.get('http://127.0.0.1:18811/api/runtime/sessions/07d63c6946df4eb68c610c0d28128918/project')).json()).project;
await page.goto(base+'/');await page.locator('#projectInput').setInputFiles({name:'guide-test.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(project))});await page.locator('[data-tab=motion]').click();await page.locator('[data-motion-page=clothes]').click();
const picker=page.locator('.motion-part-picker');await picker.locator('summary').click();await picker.locator('button').first().waitFor();assert(await picker.locator('button img').count()>4);const button=picker.locator('button').filter({hasText:'bottomwear'}).first();await button.click();assert.match(await picker.locator('summary').innerText(),/bottomwear/);
await picker.locator('summary').click();await page.screenshot({path:'output/verification/motion-part-thumbnails.png'});await picker.locator('summary').click();
await page.locator('#secondaryAddBrush').click();const overlay=page.locator('.motion-region-overlay'),bar=page.locator('.motion-region-actions');await overlay.waitFor();await bar.locator('[data-clear]').click();await bar.locator('[data-size]').fill('160');
let box=await overlay.boundingBox();assert(Math.abs(box.width/box.height-project.width/project.height)<.01,'overlay must preserve artwork aspect');
const x=box.x+box.width*.55,y=box.y+box.height*.65;await page.mouse.move(x,y);const cursor=page.locator('.motion-brush-cursor');await cursor.waitFor({state:'visible'});const cb=await cursor.boundingBox();assert(Math.abs(cb.width-cb.height)<1);assert(Math.abs(cb.x+cb.width/2-x)<2);
await page.mouse.down();assert(await cursor.isVisible());await page.mouse.move(x+box.width*.08,y,{steps:8});await page.mouse.up();await page.screenshot({path:'output/verification/motion-brush-cursor.png'});
await bar.locator('[data-erase]').click();await page.mouse.move(x,y);assert.match(await cursor.getAttribute('class'),/erasing/);await bar.locator('[data-undo]').click();await bar.locator('[data-cancel]').click();assert.equal(await overlay.count(),0);assert(!(await cursor.isVisible()));
// Aspect and cursor remain aligned after zoom and viewport resize.
await page.setViewportSize({width:1200,height:800});await page.locator('#secondaryAddBrush').click();box=await overlay.boundingBox();await page.mouse.move(box.x+box.width*.5,box.y+box.height*.5);await page.mouse.wheel(0,-180);box=await overlay.boundingBox();assert(Math.abs(box.width/box.height-1)<.01);await bar.locator('[data-cancel]').click();
const created=await page.request.post(base+'/api/runtime/sessions',{data:{project,tts:{engine:'browser'}}});assert.equal(created.status(),201);const sid=(await created.json()).session_id;
await page.setViewportSize({width:1540,height:1060});await page.goto(base+'/web/effects-editor.html?session='+sid);await page.waitForFunction(()=>!document.querySelector('#effectPreview')?.disabled,{},{timeout:120000});const root=page.locator('#avatarActions');await page.locator('#effectAdd').click();await root.locator('[data-name]').fill('照れの位置合わせ');
async function add(kind){await root.locator('[data-kind]').selectOption(kind);await root.locator('[data-add]').click();await page.waitForFunction(()=>!document.querySelector('#effectPreview').disabled);}
await add('blush');await page.locator('[data-place=blush]').click();const handle=page.locator('[data-emotion-handle]'),tools=page.locator('.avatar-preview-edit');await handle.waitFor();let h=await handle.boundingBox();const before=h.x;
await tools.locator('[data-dx="1"]').click();h=await handle.boundingBox();assert(h.x>before&&h.x-before<3,'one project pixel nudge');
await page.mouse.move(h.x+13,h.y+13);await page.mouse.down();await page.mouse.move(h.x+53,h.y+33,{steps:6});await page.mouse.up();h=await handle.boundingBox();assert(h.x>before+35,'drag shifts guide');
await page.locator('[data-look=blush_rotation]').fill('20');await page.locator('[data-look=blush_scale]').fill('1.3');await page.waitForTimeout(200);assert.match(await page.locator('.emotion-bounds').getAttribute('transform'),/rotate\(20\)/);await page.screenshot({path:'output/verification/emotion-placement-guide.png'});
await tools.locator('[data-cancel]').click();assert.equal(await page.locator('[data-look=blush_rotation]').inputValue(),'0');assert.equal(await page.locator('[data-look=blush_scale]').inputValue(),'1');assert(!(await page.locator('.emotion-position-guide').isVisible()));
await add('sweat');await page.locator('[data-place=sweat]').click();assert.equal(await page.locator('.emotion-bounds ellipse').count(),1);await tools.locator('[data-dx="1"]').click();await tools.locator('[data-done]').click();assert(!(await tools.isVisible()));await page.locator('#effectStop').click();
assert.deepEqual(errors,[]);console.log('Actual project: thumbnail selection, contained circular brush, hover/stroke/erase cursor, zoom/resize, blush/sweat guide drag, nudge, rotation, cancel and confirm passed',sid);await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
