const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs'),crypto=require('node:crypto');
const base='http://127.0.0.1:18812',id=()=>crypto.randomUUID().replaceAll('-','');
(async()=>{const browser=await chromium.launch(),page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.setDefaultTimeout(60000);page.on('pageerror',e=>errors.push(e.message));
const project=(await(await page.request.get('http://127.0.0.1:18811/api/runtime/sessions/07d63c6946df4eb68c610c0d28128918/project')).json()).project;const other=structuredClone(project);other.id=id();other.name='別ポーズ（確認用）';
const a=id(),b=id();for(const [key,p,name,kind]of [[a,project,'通常ポーズ・縁取り','outline'],[b,other,'別ポーズ・照れ','blush']]){const r=await page.request.post(base+'/api/avatar/presets',{data:{request_id:key,action:{name,project_id:p.id,kind:'bundle',behavior:'select',components:[{kind}]}}});assert.equal(r.status(),201);}
const created=await page.request.post(base+'/api/runtime/sessions',{data:{project,tts:{engine:'browser'}}});const sid=(await created.json()).session_id,url=base+'/web/player.html?session='+sid+'&prepare=1&mode=idle';
const firstId=(await(await page.request.get(base+'/api/runtime/sessions/'+sid)).json()).character_id;await page.goto(url);await page.waitForFunction(()=>document.querySelector('#runtimeCharacters [data-character]')?.options.length>0,{},{timeout:120000});
const display=await browser.newPage();display.on('pageerror',e=>errors.push(e.message));await display.goto(base+'/web/player.html?session='+sid+'&display=1');await display.waitForFunction(()=>document.querySelector('#stage canvas'),{},{timeout:120000});
const settledUrl=page.url();await page.locator('#runtimeCharacters summary').click();await page.locator('#runtimeCharacters [data-file]').setInputFiles({name:'別ポーズ（確認用）.project.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(other))});await page.waitForFunction(()=>document.querySelector('#runtimeCharacters [data-character]').options.length===2);
const otherId=await page.locator('#runtimeCharacters [data-character]').inputValue();assert.equal(await page.locator('#runtimeCharacters [data-preset] option[value="'+a+'"]').count(),0);await page.locator('#runtimeCharacters [data-preset]').selectOption(b);await page.locator('#runtimeCharacters [data-switch]').click();await page.waitForFunction(()=>document.querySelector('#runtimeCharacters [data-status]').textContent==='切り替えました',{},{timeout:120000});
assert.equal((await(await page.request.get(base+'/api/runtime/sessions/'+sid)).json()).character_id,otherId);await display.waitForFunction(()=>document.title.includes('別ポーズ'),{},{timeout:120000});assert.equal(page.url(),settledUrl);await page.screenshot({path:'output/verification/runtime-characters.png'});
const requestId=id(),body={request_id:requestId,character_id:firstId,preset_id:a};let r=await page.request.post(base+'/api/runtime/sessions/'+sid+'/characters/switch',{data:body});assert.equal(r.status(),202);
await page.waitForFunction(async([sid,rid])=>(await(await fetch('/api/runtime/sessions/'+sid+'/characters/result/'+rid)).json()).status==='completed',[sid,requestId],{timeout:120000});await display.waitForFunction(name=>document.title.includes(name),project.name,{timeout:120000});
r=await page.request.post(base+'/api/runtime/sessions/'+sid+'/characters/switch',{data:body});assert.equal((await r.json()).status,'completed');assert.equal((await page.request.post(base+'/api/runtime/sessions/'+sid+'/characters/switch',{data:{...body,preset_id:b}})).status(),409);
assert.equal((await page.request.post(base+'/api/runtime/sessions/'+sid+'/characters/switch',{data:{request_id:id(),character_id:firstId,preset_id:b}})).status(),422);
assert.deepEqual(errors,[]);for(const key of [a,b])await page.request.delete(base+'/api/avatar/presets/'+key,{data:{request_id:id(),revision:0}});fs.writeFileSync('output/verification/runtime-characters-browser.json',JSON.stringify({sid,url,errors}));console.log('Real character loading, saved action ownership, same URL player + OBS switching, retry and conflict passed');await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
