const {chromium}=require('playwright'),assert=require('node:assert/strict'),fs=require('fs');
(async()=>{const browser=await chromium.launch(),page=await browser.newPage();try{await page.goto('http://127.0.0.1:18814/');const result=await page.evaluate(async()=>{
const {applyLayerEdit,layerRevision}=await import('/web/svg-layer-edit.js'),{sanitizeSvg}=await import('/web/assets.js'),{tailEnabled,wingEnabled}=await import('/web/accessory-targets.js'),{partMotion}=await import('/web/part-motion.js'),{rigGroups}=await import('/web/rig.js');
const make=(id,color,x=0)=>({id,name:id,role:'static',x,y:0,width:100,height:100,visible:true,opacity:1,svgText:`<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 100 100"><defs><clipPath id="same"><rect width="100" height="100"/></clipPath></defs><rect width="100" height="100" fill="${color}" clip-path="url(#same)"/></svg>`});
const p={version:1,id:'00000000000000000000000000000000',name:'test',width:200,height:100,settings:{},parts:[make('p000','#ff0000'),make('p001','#0000ff',50)]};
async function pixels(parts){const data=`<svg xmlns="http://www.w3.org/2000/svg" width="200" height="100">${parts.map(p=>`<g transform="translate(${p.x} ${p.y})" opacity="${p.opacity}">${p.svgText}</g>`).join('')}</svg>`,url=URL.createObjectURL(new Blob([data],{type:'image/svg+xml'})),image=new Image();image.src=url;await image.decode();const c=document.createElement('canvas');c.width=200;c.height=100;const ctx=c.getContext('2d');ctx.drawImage(image,0,0);URL.revokeObjectURL(url);return ctx.getImageData(0,0,200,100).data;}
const before=await pixels(p.parts),rev=await layerRevision(p);applyLayerEdit(p,{operation:'merge',part_id:'p000',other_id:'p001'});const after=await pixels(p.parts);if(before.some((v,i)=>v!==after[i]))throw Error('Merge changed draw order/pixels');if(rev===await layerRevision(p))throw Error('revision not changed');
applyLayerEdit(p,{operation:'stroke',part_id:'p000',mode:'erase',color:'#ffffff',size:16,points:[[30,30],[70,30]]});const erased=await pixels(p.parts);if(erased[(30*200+50)*4+3]!==0||erased[(60*200+50)*4+3]!==255)throw Error('erase mask failed');
applyLayerEdit(p,{operation:'stroke',part_id:'p000',mode:'paint',color:'#00ff00',size:8,points:[[40,30],[60,30]]});const painted=await pixels(p.parts);if(painted[(30*200+50)*4+1]!==255||painted[(30*200+50)*4+3]!==255)throw Error('paint after erase failed');
const reopened=JSON.parse(JSON.stringify(p));reopened.parts[0].svgText=sanitizeSvg(reopened.parts[0].svgText,'load-');const loaded=await pixels(reopened.parts);if(painted.some((v,i)=>v!==loaded[i]))throw Error('save/reload changed brush');
const q={width:200,height:100,settings:{},parts:[make('p000','#fff'),make('p001','#eee')]};applyLayerEdit(q,{operation:'target',kind:'tail',target:'p001'});applyLayerEdit(q,{operation:'pivot',part_id:'p001',x:125,y:10});if(tailEnabled(q.parts[0])||!tailEnabled(q.parts[1]))throw Error('tail mapping');if(partMotion(q.parts[1],{tailAngle:12},q).rotation!==12)throw Error('tail not moving');if(rigGroups(q).length!==2)throw Error('tail not isolated');applyLayerEdit(q,{operation:'target',kind:'wing',target:'p000'});if(!wingEnabled(q.parts[0]))throw Error('wing mapping');
return {project:reopened,tail:q,checks:'pixel-identical ordered merge; independent erase and paint; ID-safe sanitization and JSON reload; arbitrary tail rotation and wing target; revision changes'};
});assert.equal(result.project.parts.length,1);assert(result.project.parts[0].rasterDisabled);fs.writeFileSync('output/verification/svg-layer-roundtrip.project.json',JSON.stringify(result.project));console.log(result.checks);
// Import through the application's actual validator, then reopen the SVG editor.
await page.locator('#projectInput').setInputFiles({name:'roundtrip.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(result.project))});await page.locator('[data-tab=edit]').click();await page.locator('[data-edit-page=parts]').click();await page.locator('#editSvgLayers').click();await page.locator('.svg-layer-editor [data-board] image').waitFor();assert.equal(await page.locator('.svg-layer-editor [data-layer] option').count(),1);await page.locator('.svg-layer-editor [data-cancel]').click();console.log('Actual app import and SVG layer editor reopen passed');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
