"""Explicit public operation catalog shared by REST discovery and the MCP adapter.

Adding a route does not automatically grant it to agents. Native process secrets,
OS dialogs and sample-only endpoints are deliberately absent.
"""

# name, method, path, purpose. Names are the stable agent-facing contract.
OPERATIONS = [
    ('output.characters','GET','/api/runtime/sessions/{sid}/characters','同じ配信画面で切り替えるキャラクターと演出の一覧'),
    ('output.add_character','POST','/api/runtime/sessions/{sid}/characters','配信画面へ追加のキャラクターを登録'),
    ('output.character_project','GET','/api/runtime/sessions/{sid}/characters/{identity}/project','登録したキャラクターの素材'),
    ('output.switch_character','POST','/api/runtime/sessions/{sid}/characters/switch','キャラクターと演出を切り替え。URLを維持'),
    ('output.character_result','GET','/api/runtime/sessions/{sid}/characters/result/{request_id}','キャラクターの読込と切替の結果'),
    ('avatar.delete', 'DELETE', '/api/avatar/presets/{identity}', 'revisionを照合して保存した演出を削除。同一要求の再送に対応'),
    ('avatar.update', 'PUT', '/api/avatar/presets/{identity}', '登録済み演出をrevision付きで更新。キー割り当てを維持'),
    ('avatar.preview', 'POST', '/api/avatar/sessions/{sid}/preview', '未保存の組み合わせ演出を一時プレビュー'),
    ('avatar.stop_preview', 'POST', '/api/avatar/sessions/{sid}/preview/stop', '指定したプレビューだけを停止して直前の演出へ戻す'),
    ('avatar.presets', 'GET', '/api/avatar/presets', 'キャラクター用のホットキー演出設定一覧'),
    ('avatar.save', 'POST', '/api/avatar/presets', '方向・時間・見た目を演出設定として保存'),
    ('avatar.trigger', 'POST', '/api/avatar/sessions/{sid}/trigger', '保存した演出をホットキーと共通処理で実行'),
    ('avatar.result', 'GET', '/api/avatar/sessions/{sid}/trigger/{request_id}', '演出の適用・描画・完了結果'),
    ('rife.status', 'GET', '/api/rife-morph/status', 'RIFE中間形状生成の利用可否。生成後の再生にRIFEは不要'),
    ('rife.generate', 'POST', '/api/rife-morph/jobs', '開閉PNGから8枚SVGまたは変形グリッドを生成。modeとrequest_idで方式・再送を指定'),
    ('rife.job', 'GET', '/api/rife-morph/jobs/{jid}', '中間形状・RIFE参照画像・進捗・失敗を取得'),
    ('rife.cancel', 'POST', '/api/rife-morph/jobs/{jid}/cancel', '中間形状の生成を中止'),
    ('project_save.choose', 'POST', '/api/project-saves/choose', '名前とrequest_idを指定してWindowsの保存先ダイアログを開く。保存先選択はユーザー操作'),
    ('project_save.write', 'POST', '/api/project-saves/{ticket}', '選択済みの保存先へプロジェクトJSONを保存。同一内容の再送に対応'),
    ('project_save.status', 'GET', '/api/project-saves/{ticket}', '保存結果・保存中・選択済み・キャンセルを取得'),
    ('projects.list', 'GET', '/api/projects', '変換済みプロジェクト一覧'),
    ('projects.get', 'GET', '/api/projects/{pid}', 'SVG・素材URLを含むプロジェクト'),
    ('projects.import', 'POST', '/api/import', 'PNGまたはPSDを変換（multipart）'),
    ('projects.import_hybrid', 'POST', '/api/import/hybrid', '元絵・PSD・任意の差分とDepthを変換（multipart）'),
    ('projects.job', 'GET', '/api/jobs/{jid}', '変換の進捗・完了・失敗を確認'),
    ('materials.list', 'GET', '/api/materials', '補正中の素材一覧'),
    ('materials.create', 'POST', '/api/materials', '画像・PSDを素材として登録（multipart）'),
    ('materials.get', 'GET', '/api/materials/{mid}', 'レイヤー・revision・Depthの状態'),
    ('materials.save', 'PUT', '/api/materials/{mid}', 'revisionを照合してレイヤーの補正を保存'),
    ('materials.add', 'POST', '/api/materials/{mid}/add', '追加レイヤー・候補を登録（multipart）'),
    ('materials.extract', 'POST', '/api/materials/{mid}/extract', '指定領域を新しいレイヤーに切り出す'),
    ('materials.repair_context', 'POST', '/api/materials/{mid}/assist-region', '補修用の参照画像・マスクZIPを作る'),
    ('materials.export', 'POST', '/api/materials/{mid}/export', '補正済みPSD・作業ZIPを保存'),
    ('materials.restore', 'POST', '/api/materials/restore', '作業ZIPを新しい素材として復元（multipart）'),
    ('materials.convert', 'POST', '/api/materials/{mid}/convert', '補正済み素材をSVGへ変換'),
    ('inference.status', 'GET', '/api/material-inference/status', 'See-ThroughとDepth生成環境の利用可否'),
    ('inference.start', 'POST', '/api/material-inference/jobs', '分割または補正後のDepth生成を開始'),
    ('inference.job', 'GET', '/api/material-inference/jobs/{jid}', '生成の進捗・完了・失敗を確認'),
    ('inference.cancel', 'POST', '/api/material-inference/jobs/{jid}/cancel', '指定した生成処理を中止'),
    ('editor.status', 'GET', '/api/control/status', '編集画面の接続・実行中の操作'),
    ('editor.project', 'GET', '/api/control/project', '編集画面が公開した最新スナップショット'),
    ('editor.command', 'POST', '/api/control/commands', '再生・目口・動き・補正・読込・保存・書出し。接続した編集画面が必要'),
    ('editor.result', 'GET', '/api/control/commands/{cid}', '操作の実行結果。202受付を完了扱いしない'),
    ('assist.info', 'GET', '/api/assist/info', '目口と動きのAI補正ワークフロー仕様'),
    ('assist.sessions', 'GET', '/api/assist/sessions', '保存した補正セッション一覧'),
    ('assist.session', 'GET', '/api/assist/sessions/{sid}', '補正候補・比較画像・revision'),
    ('assist.input', 'GET', '/api/assist/inputs/{iid}', '登録済み入力と補正依頼'),
    ('assist.start', 'POST', '/api/assist/inputs/{iid}/start', '登録済み入力から変換を開始'),
    ('assist.asset', 'GET', '/api/assist/assets/{aid}', '補修用画像の配置情報'),
    ('assist.import_asset', 'POST', '/api/assist/asset-requests/{rid}/import', '外部で生成した補修PNGを登録（multipart）'),
    ('output.list', 'GET', '/api/runtime/sessions', '出力の接続状態・発話・表情'),
    ('output.create', 'POST', '/api/runtime/sessions', '出力セッションを作成。返るplayer_urlを開く工程は別途必要'),
    ('output.status', 'GET', '/api/runtime/sessions/{sid}', '指定出力の状態'),
    ('output.project', 'GET', '/api/runtime/sessions/{sid}/project', '出力中のプロジェクト'),
    ('output.reception', 'POST', '/api/runtime/sessions/{sid}/reception', '固定発話APIの受け取り先を設定'),
    ('output.voice', 'PUT', '/api/runtime/sessions/{sid}/voice', '音声設定を更新。voice_revisionをrevisionに指定。発話中・競合は409'),
    ('output.speech', 'POST', '/api/runtime/sessions/{sid}/speech', '発話・割込・停止。request_idで重複を防ぐ'),
    ('output.speech_result', 'GET', '/api/runtime/sessions/{sid}/speech/{request_id}', '発話の実行結果'),
    ('output.expression', 'POST', '/api/runtime/sessions/{sid}/expression', '表情と強さを選ぶ。request_idで重複を防ぐ'),
    ('output.expression_result', 'GET', '/api/runtime/sessions/{sid}/expression/{request_id}', '出力画面が表情を適用した結果'),
    ('output.close', 'POST', '/api/runtime/sessions/{sid}/close', '指定出力を終了'),
    ('output.effects', 'GET', '/api/runtime/effects', '演出プリセットと制約を確認'),
    ('output.effect', 'POST', '/api/runtime/sessions/{sid}/effect', '消滅・登場・通信中・幸せの光。noneで復元。request_idで重複を防ぐ'),
    ('output.effect_result', 'GET', '/api/runtime/sessions/{sid}/effect/{request_id}', '演出の開始・完了・中断・失敗を確認'),
    ('voices.list', 'POST', '/api/tts/voices', '音声エンジンの声一覧を取得'),
    ('stage.library', 'GET', '/api/stage/library', '登録した演出画像・演技プリセット一覧'),
    ('stage.upload', 'POST', '/api/stage/assets', '外部生成したPNG・JPEG・WebPを演出画像として登録（multipart）'),
    ('stage.save_preset', 'POST', '/api/stage/presets', '演技の時間順レシピを新しいプリセットとして保存'),
    ('stage.preset', 'GET', '/api/stage/presets/{pid}', '保存した演技レシピを取得'),
    ('stage.state', 'GET', '/api/stage/sessions/{sid}', '通常設定・AI制御モード・実行中の演技・revision'),
    ('stage.configure', 'PUT', '/api/stage/sessions/{sid}', '通常設定とAI制御モードを更新。fixedで演技を解除して復元'),
    ('stage.perform', 'POST', '/api/stage/sessions/{sid}/perform', '画像・字幕・表情・動きを時間順に演じる。AIモードが必要'),
    ('stage.result', 'GET', '/api/stage/sessions/{sid}/perform/{request_id}', '演技の描画開始・完了・中断・失敗を確認'),
    ('voices.models', 'POST', '/api/tts/models', '音声エンジンのモデル一覧を取得'),
]


def catalog():
    return [dict(name=name, method=method, path=path, description=description,
                 read_only=method == 'GET' or name.startswith('voices.'))
            for name, method, path, description in OPERATIONS]
