import {installMaterialRegions} from './material-region-ui.js';
import {installMaterialInference} from './material-inference-ui.js';
import {materialTags,moveMaterial,parentAllowed,materialChecks,localCrop,materialGroups} from './material-state.js';
const $=id=>document.getElementById(id),ctx=$('canvas').getContext('2d'),images=new Map();
let state=null,baseline=null,selected=null,dirty=false,busy=false,undo=[],area=null,drag=null,compare=false;
const api='/api/materials';
let inference,regions;
function message(text,error=false){$('status').textContent=text;$('status').classList.toggle('error',error);}
async function request(url,options){const r=await fetch(url,options);if(!r.ok){let e;try{e=(await r.json()).detail;}catch{}throw Error(typeof e==='string'?e:'処理に失敗しました。設定を確認してください。');}return r.json();}
function run(fn){return async e=>{if(busy)return;busy=true;renderControls();try{await fn(e);}catch(error){message(error.message,true);}finally{busy=false;renderControls();}};}
function checkpoint(){undo.push(structuredClone(state.layers));if(undo.length>30)undo.shift();dirty=true;compare=false;}
function url(p){return `${api}/${state.id}/files/${p.asset}`;}
async function loadImages(){await Promise.all(state.layers.map(p=>{if(images.has(p.asset))return;return new Promise((resolve,reject)=>{const im=new Image();im.onload=()=>{images.set(p.asset,im);resolve();};im.onerror=()=>reject(Error('パーツ画像を読み込めません'));im.src=url(p);});}));}
async function adopt(value,first=false){state=value;selected=state.layers.find(p=>p.id===selected)?.id||state.layers.at(-1)?.id;dirty=false;await loadImages();if(first){baseline=structuredClone(state.layers);undo=[];area=null;}$('entry').hidden=true;$('workshop').hidden=false;$('title').textContent=state.name;history.replaceState(null,'','?material='+state.id);render();}
function renderControls(){inference?.refresh(busy);regions?.refresh(busy);const p=state?.layers.find(p=>p.id===selected);$('save').disabled=busy||!state||!dirty;$('convert').disabled=$('export').disabled=busy||!state;$('undo').disabled=busy||!undo.length;$('fields').disabled=busy||!p;$('saveState').textContent=state?(dirty?'未保存の変更あり':'保存済み · '+state.revision):'';if(!p)return;for(const id of ['layerName','tag','x','y','scale','opacity','parent','repair','visible','depth','forward','backward','crop','uncrop'])$(id).disabled=busy||p.locked;$('locked').disabled=busy;$('crop').disabled=busy||p.locked||!area;$('clearArea').disabled=!area;$('uncrop').disabled=busy||p.locked||!p.crop;}
function render(){if(!state)return;const rows=[...state.layers].reverse().map(p=>{const b=document.createElement('button');b.className='layer-row'+(p.id===selected?' active':'')+(!p.visible?' off':'');const img=document.createElement('img');img.src=url(p);img.alt='';const text=document.createElement('span');text.textContent=p.name;const detail=document.createElement('small');detail.textContent=(p.visible?'表示':'非表示')+' · '+(materialTags[p.tag]||p.tag)+(p.locked?' · ロック':'');text.append(detail);b.append(img,text);b.onclick=()=>{selected=p.id;area=null;render();};return b;});$('layers').replaceChildren(...rows);const p=state.layers.find(p=>p.id===selected);if(p){$('selectionTitle').textContent=p.name;$('layerName').value=p.name;for(const id of ['tag','x','y','depth'])$(id).value=p[id];for(const id of ['visible','locked','repair'])$(id).checked=p[id];$('scale').value=Math.round(p.scale*100);$('opacity').value=Math.round(p.opacity*100);$('depthValue').value=p.depth;$('parent').replaceChildren(new Option('役割から決める',''),...state.layers.filter(v=>v.id!==p.id&&parentAllowed(state.layers,p.id,v.id)).map(v=>new Option(v.name,v.id)));$('parent').value=p.parent||'';}$('checks').replaceChildren(...materialChecks(state).map(text=>{const li=document.createElement('li');li.textContent=text;return li;}));$('compare').setAttribute('aria-pressed',String(compare));$('compare').textContent=compare?'補正中に戻る':'読み込み時と比較';draw();renderControls();}
function draw(){if(!state)return;const canvas=$('canvas'),scale=Math.min(1,1000/Math.max(state.width,state.height));canvas.width=Math.round(state.width*scale);canvas.height=Math.round(state.height*scale);ctx.setTransform(scale,0,0,scale,0,0);ctx.clearRect(0,0,state.width,state.height);for(const p of materialGroups(compare?baseline:state.layers).flat()){const im=images.get(p.asset);if(!p.visible||!im||/^(closed-|mouth-closed)/.test(p.tag))continue;ctx.save();ctx.translate(p.x,p.y);ctx.scale(p.scale,p.scale);ctx.globalAlpha=p.opacity;if(p.crop){ctx.beginPath();ctx.rect(p.crop[0],p.crop[1],p.crop[2]-p.crop[0],p.crop[3]-p.crop[1]);ctx.clip();}ctx.drawImage(im,0,0);ctx.restore();}if(!compare){const p=state.layers.find(p=>p.id===selected),im=p&&images.get(p.asset);if(im){ctx.strokeStyle='#647cdb';ctx.lineWidth=2/scale;ctx.setLineDash([5/scale,4/scale]);ctx.strokeRect(p.x,p.y,im.width*p.scale,im.height*p.scale);ctx.setLineDash([]);}if(area){ctx.fillStyle='#587fe52b';ctx.strokeStyle='#4b71d0';ctx.lineWidth=2/scale;ctx.fillRect(area[0],area[1],area[2]-area[0],area[3]-area[1]);ctx.strokeRect(area[0],area[1],area[2]-area[0],area[3]-area[1]);}}}
async function save(){if(!dirty)return;state=await request(`${api}/${state.id}`,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({revision:state.revision,name:state.name,layers:state.layers})});dirty=false;renderControls();}
async function list(){const values=await request(api);$('recent').replaceChildren(new Option('保存済みの素材を選ぶ',''),...values.map(v=>new Option(v.name+' · '+v.layers.length+'パーツ',v.id)));}
$('tag').replaceChildren(...Object.entries(materialTags).map(([k,v])=>new Option(v,k)));
$('createFile').onchange=run(async e=>{const file=e.target.files[0];if(!file)return;message('素材を読み込んでいます…');const body=new FormData();body.append('file',file);await adopt(await request(api,{method:'POST',body}),true);message('読み込みました。パーツの役割と重なりを確認してください。');});
$('recent').onchange=run(async e=>{if(e.target.value)await adopt(await request(api+'/'+e.target.value),true);});
for(const [id,candidate] of [['addFile',false],['candidateFile',true]])$(id).onchange=run(async e=>{const file=e.target.files[0];if(!file)return;await save();const body=new FormData();body.append('file',file);body.append('revision',state.revision);body.append('candidate',candidate);await adopt(await request(`${api}/${state.id}/add`,{method:'POST',body}));undo=[];e.target.value='';message(candidate?'候補を非表示で追加しました。採用するパーツを表示してください。':'画像を追加しました。役割や補修先を選んでください。');});
for(const id of ['layerName','tag','x','y','scale','opacity','visible','locked','parent','repair','depth'])$(id).onchange=()=>{const p=state.layers.find(p=>p.id===selected);if(!p||busy||(p.locked&&id!=='locked'))return;checkpoint();let value=['visible','locked','repair'].includes(id)?$(id).checked:['x','y','scale','opacity','depth'].includes(id)?Number($(id).value):$(id).value;if(typeof value==='number'&&!Number.isFinite(value)){undo.pop();return;}if(id==='scale'||id==='opacity')value/=100;p[id==='layerName'?'name':id]=id==='parent'?(value||null):value;render();};
$('save').onclick=run(async()=>{await save();message('補正内容を保存しました。');});
$('undo').onclick=()=>{if(undo.length){state.layers=undo.pop();dirty=true;compare=false;render();}};
for(const [id,delta] of [['forward',1],['backward',-1]])$(id).onclick=()=>{checkpoint();state.layers=moveMaterial(state.layers,selected,delta);render();};
$('compare').onclick=()=>{compare=!compare;render();};
$('clearArea').onclick=()=>{area=null;render();};
$('crop').onclick=()=>{try{const p=state.layers.find(p=>p.id===selected),im=images.get(p.asset),crop=localCrop(area,p,[im.width,im.height]);checkpoint();p.crop=crop;area=null;render();}catch(e){message(e.message,true);}};
$('uncrop').onclick=()=>{checkpoint();state.layers.find(p=>p.id===selected).crop=null;render();};
function point(e){const r=$('canvas').getBoundingClientRect();return [(e.clientX-r.left)/r.width*state.width,(e.clientY-r.top)/r.height*state.height];}
$('canvas').onpointerdown=e=>{if(!state||compare||busy)return;const [x,y]=point(e);if($('selectArea').checked){drag=[x,y];area=[x,y,x,y];$('canvas').setPointerCapture(e.pointerId);return;}const hits=[...state.layers].reverse().filter(p=>{if(!p.visible)return false;const im=images.get(p.asset),ix=(x-p.x)/p.scale,iy=(y-p.y)/p.scale;if(!im||ix<0||iy<0||ix>=im.width||iy>=im.height||p.crop&&(ix<p.crop[0]||iy<p.crop[1]||ix>=p.crop[2]||iy>=p.crop[3]))return false;const c=document.createElement('canvas');c.width=c.height=1;const hit=c.getContext('2d');hit.drawImage(im,Math.floor(ix),Math.floor(iy),1,1,0,0,1,1);return hit.getImageData(0,0,1,1).data[3]>12;});if(hits.length){selected=hits[0].id;render();}$('hits').replaceChildren(...hits.map(p=>{const b=document.createElement('button');b.textContent=p.name;b.onclick=()=>{selected=p.id;render();};return b;}));};
$('canvas').onpointermove=e=>{if(drag){area=[...drag,...point(e)];draw();}};
for(const event of ['pointerup','pointercancel'])$('canvas').addEventListener(event,()=>{drag=null;renderControls();});
$('export').onclick=run(async()=>{await save();const result=await request(`${api}/${state.id}/export`,{method:'POST'});$('exports').replaceChildren(...[['psd','補正済みPSDをダウンロード'],['manifest','パーツ設定をダウンロード'],['bundle','作業一式ZIP（再開用）']].map(([key,label])=>{const a=document.createElement('a');a.href=result[key];a.download=state.name+(key==='psd'?'.psd':key==='bundle'?'.zip':'.json');a.textContent=label;return a;}));message('補正済みPSDとパーツ設定を保存しました。');});
$('convert').onclick=run(async()=>{await save();await inference.ensureDepth();const {jobId}=await request(`${api}/${state.id}/convert`,{method:'POST'});for(;;){const job=await request('/api/jobs/'+jobId);message(job.message);if(job.state==='error')throw Error(job.message);if(job.state==='done'){location.assign('/?prepared='+job.projectId);return;}await new Promise(r=>setTimeout(r,800));}});
$('home').onclick=e=>{if(dirty&&!confirm('未保存の補正があります。保存せずにメインメニューへ戻りますか？'))e.preventDefault();};
window.addEventListener('beforeunload',e=>{if(dirty){e.preventDefault();e.returnValue='';}});
regions=installMaterialRegions({state:()=>state,part:()=>state?.layers.find(p=>p.id===selected),area:()=>area,size:()=>{const im=images.get(state.layers.find(p=>p.id===selected).asset);return [im.width,im.height];},save,request,run,adopt,checkpoint,render,message,remove:id=>{state.layers=state.layers.filter(p=>p.id!==id);selected=state.layers.at(-1).id;}});
inference=installMaterialInference({state:()=>state,save,adopt,request,run,message,checkpoint,render});
void run(async()=>{await list();const id=new URLSearchParams(location.search).get('material');if(id)await adopt(await request(api+'/'+encodeURIComponent(id)),true);})();
